// @ts-nocheck
/**
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import events_emitter from '@ohos.emitter'

@Entry
@Component
struct SearchExample {
  @State textFontValue: number= 10;
  @State searchButtonValue: string= ''
  @State caretPositionValue: string= 10
  private stateChangCallBack = (eventData) => {
    console.info("search page state change called:" + JSON.stringify(eventData));
    if (eventData != null) {
      if (eventData.data.textFontValue != null) {
        this.textFontValue = eventData.data.textFontValue;
      }
      if (eventData.data.searchButtonValue != null) {
        this.searchButtonValue = eventData.data.searchButtonValue;
      }
      if (eventData.data.caretPositionValue != null) {
        this.caretPositionValue = eventData.data.caretPositionValue;
      }
    }
  }

  onPageShow() {
    console.info('span page show called');
    var stateChangeEvent = {
      eventId: 40,
      priority: events_emitter.EventPriority.LOW
    }
    events_emitter.on(stateChangeEvent, this.stateChangCallBack);
  }

  build() {
    Column() {
      Navigation() {
        Search({ value: '', placeholder: "", searchButton: "bbb" }).width('85%').margin(26)
          .key('search')
      }
    }
  }
}


